### ISSUE TITLE
Doesn't work well on Edge

### ISSUE THREAD

**Issue by r0bd0g** [scattertv/zootr-sim#1]
The items on the tracker all start lit, so you can't tell what items you've actually collected.

**Comment by WernerBureau** [comment]
I'm using Edge right now and I don't seem to have this issue.

**Comment by r0bd0g** [comment]
Me neither, anymore?

**Comment by scattertv** [comment]
Fixed this accidentally, lol. I was previously using a background image blending mode to dim the images, but switched to using webkit's filter property when I made dark mode because it wasn't dependent on the background color. I actually didn't notice this issue, must have missed the email. But thanks for reporting!

**Comment by r0bd0g** [comment]
Nice.
